# Generated by Django 3.1.2 on 2020-10-28 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('about_me', models.TextField(max_length=500)),
                ('fitness_goal', models.CharField(choices=[('Improve My Overall Health', 'Improve My Overall Health'), ('Improve My Mental Health', 'Improve My Mental Health'), ('Spread Awareness About Health and Fitness', 'Spread Awareness About Health and Fitness'), ('Track My Calorie Intake and Burn', 'Track My Calorie Intake and Burn'), ('Give Health Consultancy', 'Give Health Consultancy'), ('Body Building', 'Body Building'), ('Other', 'Other')], default='Improve My Overall Health', max_length=50)),
                ('user_type', models.CharField(choices=[('Fitness Enthusiast', 'Fitness Enthusiast'), ('Fitness Intstructor', 'Fitness Intstructor'), ('Fitness Blogger', 'Fitness Blogger'), ('Yoga Intstructor', 'Yoga Intstructor'), ('Nutritionist', 'Nutritionist'), ('Physiotherapist', 'Physiotherapist'), ('Psychologist', 'Psychologist'), ('Ayurvedic Doctor', 'Ayurvedic Doctor'), ('Other Specialized Doctor', 'Other Specialized Doctor')], default='Fitness Enthusiast', max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('U', 'Unknown')], default='U', max_length=1)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(5)])),
                ('height', models.FloatField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(20)])),
                ('weight', models.FloatField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(5)])),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
