# Generated by Django 3.1.2 on 2020-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name_plural': 'User Details'},
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='city',
            field=models.CharField(default='Rohtak', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='lakshaydhingra32969@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='firstname',
            field=models.CharField(default='Lakshay', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(default='Dh', max_length=100),
            preserve_default=False,
        ),
    ]
