# Generated by Django 3.1.2 on 2020-11-02 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201101_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='about_me',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(5)]),
        ),
    ]
