# Generated by Django 3.1.2 on 2020-11-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201102_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='lastname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
