# Generated by Django 3.1.2 on 2020-11-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201102_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='blood_group',
            field=models.CharField(choices=[('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('HH+ve', 'HH+ve'), ('HH-ve', 'HH-ve'), ('U', 'Unknown')], default='U', max_length=5),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='race',
            field=models.CharField(choices=[('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Black or African American', 'Black or African American'), ('White or Caucasian', 'White or Caucasian'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('U', 'Unknown')], default='U', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='total_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='fitness_goal',
            field=models.CharField(choices=[('Improve My Overall Health', 'Improve My Overall Health'), ('Mental Wellness', 'Mental Wellness'), ('Spread Awareness About Health and Fitness', 'Spread Awareness About Health and Fitness'), ('Reduce Weight', 'Reduce Weight'), ('Gain Weight', 'Gain Weight'), ('Maintain Weight', 'Maintain Weight'), ('Gain Height', 'Gain Height'), ('Give Health Consultancy', 'Give Health Consultancy'), ('Body Building', 'Body Building'), ('Other', 'Other')], default='Improve My Overall Health', max_length=50),
        ),
    ]
